ServerEvents.recipes(event => {
//vanilla additions
//slime crop
    event.recipes.botanypots.crop(
        "minecraft:slime_ball",
        ["slimeSoil"],
        {block:"minecraft:slime_block"},
        [
        Item.of("minecraft:slime_ball")
        .withChance(1)
        .withRolls(1,3)],
        2500,
        1
    )
//brick crop
    event.recipes.botanypots.crop(
        "minecraft:brick",
        ["brickSoil"],
        {block:"minecraft:bricks"},
        [
        Item.of("minecraft:brick")
        .withChance(1)
        .withRolls(1,4)],
        2500,
        1
    )
//clay crop
    event.recipes.botanypots.crop(
        "minecraft:clay_ball",
        ["claySoil"],
        {block:"minecraft:clay"},
        [
        Item.of("minecraft:clay_ball")
        .withChance(1)
        .withRolls(1,4)],
        2500000,
        1
    )
//nether brick crop
    event.recipes.botanypots.crop(
        "minecraft:nether_brick",
        ["netherbrickSoil"],
        {block:"minecraft:nether_bricks"},
        [
        Item.of("minecraft:nether_brick")
        .withChance(1)
        .withRolls(1,4)],
        25000,
        1
    )
//glowstone store
    event.recipes.botanypots.crop(
        "minecraft:glowstone_dust",
        ["glowstoneSoil"],
        {block:"minecraft:glowstone"},
        [
        Item.of("minecraft:glowstone_dust")
        .withChance(1)
        .withRolls(1,4),
        Item.of("minecraft:blaze_rod")
        .withChance(.25)
        .withRolls(1,1)   
        ],
        2500000,
        1
    )
//amethyst crop
    event.recipes.botanypots.crop(
        "minecraft:amethyst_shard",
        ["amethystSoil"],
        {block:"minecraft:amethyst_cluster"},
        [
        Item.of("minecraft:amethyst_shard")
        .withChance(1)
        .withRolls(1,4)  
        ],
        25000,
        1
    )
//vanilla ore crops
//iron crop
    event.recipes.botanypots.crop(
        "#forge:ingots/iron",
        ["ironSoil"],
        {block:"minecraft:iron_ore"},
        [
        Item.of("minecraft:raw_iron")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//gold crop
    event.recipes.botanypots.crop(
        "#forge:ingots/gold",
        ["goldSoil"],
        {block:"minecraft:gold_ore"},
        [
        Item.of("minecraft:raw_gold")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//copper crop
    event.recipes.botanypots.crop(
        "#forge:ingots/copper",
        ["copperSoil"],
        {block:"minecraft:copper_ore"},
        [
        Item.of("minecraft:raw_copper")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//diamond crop
    event.recipes.botanypots.crop(
        "minecraft:diamond",
        ["diamondSoil"],
        {block:"minecraft:diamond_ore"},
        [
        Item.of("minecraft:diamond")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//redstone crop
    event.recipes.botanypots.crop(
        "minecraft:redstone",
        ["redstoneSoil"],
        {block:"minecraft:redstone_ore"},
        [
        Item.of("minecraft:redstone")
        .withChance(1)
        .withRolls(3,6)],
        3000,
        1
    )
//lapis crop
    event.recipes.botanypots.crop(
        "minecraft:lapis_lazuli",
        ["lapisSoil"],
        {block:"minecraft:lapis_ore"},
        [
        Item.of("minecraft:lapis_lazuli")
        .withChance(1)
        .withRolls(3,6)],
        3000,
        1
    )
//quartz crop
    event.recipes.botanypots.crop(
        "minecraft:quartz",
        ["quartzSoil"],
        {block:"minecraft:nether_quartz_ore"},
        [
            Item.of("minecraft:quartz")
            .withChance(1)
            .withRolls(3,6)],
            3000,
            1
    )
//modded ore crops
//tin crop
    event.recipes.botanypots.crop(
        "#forge:ingots/tin",
        ["tinSoil"],
        {block:"common_ore_library:tin_ore"},
        [
        Item.of("common_ore_library:raw_tin")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//silver crop
    event.recipes.botanypots.crop(
        "#forge:ingots/silver",
        ["silverSoil"],
        {block:"common_ore_library:silver_ore"},
        [
        Item.of("common_ore_library:raw_silver")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//nickel crop
    event.recipes.botanypots.crop(
        "#forge:ingots/nickel",
        ["nickelSoil"],
        {block:"common_ore_library:nickel_ore"},
        [
        Item.of("common_ore_library:raw_nickel")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//lead crop
    event.recipes.botanypots.crop(
        "#forge:ingots/lead",
        ["leadSoil"],
        {block:"common_ore_library:lead_ore"},
        [
        Item.of("common_ore_library:raw_lead")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//platinum crop
    event.recipes.botanypots.crop(
        "#forge:ingots/platinum",
        ["platinumSoil"],
        {block:"common_ore_library:platinum_ore"},
        [
        Item.of("common_ore_library:raw_platinum")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//zinc crop
    event.recipes.botanypots.crop(
        "#forge:ingots/zinc",
        ["zincSoil"],
        {block:"common_ore_library:zinc_ore"},
        [
        Item.of("common_ore_library:raw_zinc")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//refined storage crops
//quartz enriched iron crop
    event.recipes.botanypots.crop(
        "refinedstorage:quartz_enriched_iron",
        ["quartzEnrichedIronSoil"],
        {block:"minecraft:iron_ore"},
        [
        Item.of("refinedstorage:quartz_enriched_iron")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//ender io crops
//copper alloy crop
    event.recipes.botanypots.crop(
        "#forge:ingots/copper_alloy",
        ["copperAlloySoil"],
        {block:"enderio:copper_alloy_block"},
        [
        Item.of("enderio:copper_alloy_ingot")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//energetic alloy crop
    event.recipes.botanypots.crop(
        "#forge:ingots/energetic_alloy",
        ["energeticAlloySoil"],
        {block:"enderio:energetic_alloy_block"},
        [
        Item.of("enderio:energetic_alloy_ingot")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//vibrant alloy crop
    event.recipes.botanypots.crop(
        "#forge:ingots/vibrant_alloy",
        ["vibrantAlloySoil"],
        {block:"enderio:vibrant_alloy_block"},
        [
        Item.of("enderio:vibrant_alloy_ingot")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//redstone alloy crop
    event.recipes.botanypots.crop(
        "#forge:ingots/redstone_alloy",
        ["redstoneAlloySoil"],
        {block:"enderio:redstone_alloy_block"},
        [
        Item.of("enderio:redstone_alloy_ingot")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//conductive alloy crop
    event.recipes.botanypots.crop(
        "#forge:ingots/conductive_alloy",
        ["conductiveAlloySoil"],
        {block:"enderio:conductive_alloy_block"},
        [
        Item.of("enderio:conductive_alloy_ingot")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//pulsating alloy crop
    event.recipes.botanypots.crop(
        "#forge:ingots/pulsating_alloy",
        ["pulsatingAlloySoil"],
        {block:"enderio:pulsating_alloy_block"},
        [
        Item.of("enderio:pulsating_alloy_ingot")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//dark steel crop
    event.recipes.botanypots.crop(
        "#forge:ingots/dark_steel",
        ["darkSteelSoil"],
        {block:"enderio:dark_steel_block"},
        [
        Item.of("enderio:dark_steel_ingot")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//soularium crop
    event.recipes.botanypots.crop(
        "#forge:ingots/soularium",
        ["soulariumSoil"],
        {block:"enderio:soularium_block"},
        [
        Item.of("enderio:soularium_ingot")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//end steel crop
    event.recipes.botanypots.crop(
        "#forge:ingots/end_steel",
        ["endSteelSoil"],
        {block:"enderio:end_steel_block"},
        [
        Item.of("enderio:end_steel_ingot")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//grains of infinity crop
    event.recipes.botanypots.crop(
        "#forge:dust/grains_of_infinity",
        ["obsidianSoil"],
        {block:"minecraft:deepslate"},
        [
        Item.of("enderio:grains_of_infinity")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )
//pulsating crystal crop
    event.recipes.botanypots.crop(
        "#forge:gems/pulsating_crystal",
        ["diamondSoil"],
        {block:"enderio:pulsating_alloy_block"},
        [
        Item.of("enderio:pulsating_crystal")
        .withChance(1)
        .withRolls(1,1)],
        4000,
        1
    )
//vibrant crystal crop
    event.recipes.botanypots.crop(
        "#forge:gems/vibrant_crystal",
        ["emeraldSoil"],
        {block:"enderio:vibrant_alloy_block"},
        [
        Item.of("enderio:vibrant_crystal")
        .withChance(1)
        .withRolls(1,1)],
        4000,
        1
    )
/*//mystical agrculture crops
//prosperity crop
    event.recipes.botanypots.crop(
        "mysticalagriculture:prosperity_ingot",
        ["prosperitySoil"],
        {block:"mysticalagriculture:prosperity_ore"},
        [
        Item.of("mysticalagriculture:prosperity_shard")
        .withChance(1)
        .withRolls(1,3)],
        3000,
        1
    )*/
})